### ISSUE TITLE
Style element when using Angular Material

### ISSUE THREAD

**Issue by sorskoot** [MSOpenTech/winstore-jscompat#15]
Hi,

I'm trying to use the Angular-Material library in an Apache Cordova app. On my Windows Phone (8.1) angular-material tries to insert a style block to the <head> section. Winstore-jscompat wraps this style block in a \<head\> and \<body\> instead of a leaving it just the \<style\>, which makes the whole thing unusable. 

The result looks like this:
> \<style\>\<head\>\</head\>\<body class="ng-binding"\>/\*lots of generated styles\*/\</body\>\</style\>

When I do not include winstore-jscompat.js the styling of the app works as expected, but the app breaks in other areas where html is injected.

**Comment by xirzec** [comment]
@sorskoot  What version of winstore-jscompat.js are you using? This issue should be fixed in the latest master.

**Comment by sorskoot** [comment]
@xirzec I was using the version that came with the Cordova tools in Visual Studio. I didn't realize there could be a newer version... Using the latest version fixed the issue. Thanks.
