### ISSUE TITLE
Image and SVG image files are not loading properly. 

### ISSUE THREAD

**Issue by bharathibtch** [MSOpenTech/winstore-jscompat#21]
Hi All, 

I have referred this winstore-jscompat script file, now the navigation between pages are working fine. But images and svg images are not loading properly. 

Could you please let me know if you have any solutions?. 

Regards,
Bharathi D

**Comment by DaniloCouto** [comment]
I got the same issue.
I fixed that way:

On you app module config , add this line.

``` javascript
$compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|http?|local|file|filesystem|blob|cdvfile|data):/);
```

I don't read much about it but it will ... sanitize the image links and it will work.
Hope that I helped

**Comment by bharathibtch** [comment]
@DaniloCouto  Thanks :)
