### ISSUE TITLE
Extra body tags in the rendered html.

### ISSUE THREAD

**Issue by Fishes** [MSOpenTech/winstore-jscompat#8]
When a directive is added the added html tags are surrounded in an extra body tag. And preceded by an extra head tag.

**Comment by wbreza** [comment]
Thanks for fixing this.  I was going crazy trying to find out where the extra body tags were coming from.  This was screwing up any component JS that was referencing document.body as it was pointing to the extra (empty) body tag.  I'm looking forward to seeing this PR get into the master source.

**Comment by xirzec** [comment]
I created a fix in #11. @wbreza @Fishes  can you give it a try?

**Comment by Fishes** [comment]
The fix works for the specified problem. 
But in my project I include WinJS components and these fail with this fix.
Inititalizing the appBar and adding buttons fails at line 133:13 with the error Invallid pointer.
Sorry

**Comment by wbreza** [comment]
Looks like it works for elements that get injected under the body, but it doesn't work when elements are dynamically injected into the <head/> of the page.

For example, when using this with angular, the default style block that angular attempts to injects into the head of the page does not work.

**Comment by xirzec** [comment]
@Fishes - Looks like there is a problem in AppBar specifically: https://github.com/winjs/winjs/issues/899

@wbreza - How would that work if you are calling innerHTML on a documentElement? Your code will always strip out `<body>` and `<head>` tags.

**Comment by wbreza** [comment]
@xirzec - I haven't tested that case.  I'll update again when I have some time to test it out.

**Comment by xirzec** [comment]
@wbreza - Can you give an example of what angular is doing to inject styles? I updated #11 with a guess, but I wasn't sure if they were injecting a tag like `<style>` that document wants to group in `<head>` but they wanted to put in the `<body>` or something.

**Comment by xirzec** [comment]
@Fishes  - I was wrong about it being an AppBar problem, the problem was actually because AppBar sets an empty string as innerHTML. I updated #11 to work around that as well.

**Comment by wbreza** [comment]
@xirzec - Take a look at the last line of [Angular](https://github.com/angular/bower-angular/blob/master/angular.js) and you'll see they are finding the 'head' element and prepending a style block.

**Comment by xirzec** [comment]
@wbreza Thanks for the pointer. Yep, they're inserting a `<style>` tag into a `<div>`'s innerHTML.

**Comment by xirzec** [comment]
@wbreza  Alright! I think I have something workable in #11 - it works with Angular, it works with AppBar, it works with a simple div, it works with a new document element.
